name: OWASP Zap
on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
jobs:
  owasp-zap:
    name: Analyze with OWASP Zap API
    runs-on: ubuntu-20.04
    continue-on-error: true
    steps:
      - uses: actions/checkout@v4.1.1
      - name: Set up JDK 17
        uses: actions/setup-java@v4.0.0
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Cache Gradle packages
        uses: actions/cache@v3.3.3
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle') }}
          restore-keys: ${{ runner.os }}-gradle
      - name: Run OWASP Zap
        run: ./gradlew runOwaspZap
      - name: docker-compose down
        if: always()
        run: ./gradlew stopOwaspZap
      - name: Trim Summary Report
        run: |
          sudo sed '/## Alert Detail/Q' ./opendcs-rest-api-jetty/build/test-results/owasp/zap_report.md > ./zap_report_summary.md
      - name: Generate GitHub Job Summary
        uses: x-color/github-actions-job-summary@v0.1.1
        with:
          file: ./zap_report_summary.md
          vars: |
            empty: empty
      - name: Upload Full HTML Report
        uses: actions/upload-artifact@v4.2.0
        with:
          name: zap_report.html
          path: ./opendcs-rest-api-jetty/build/test-results/owasp/zap_report.html
          retention-days: 1
          if-no-files-found: error
