name: Swagger/OpenAPI Specification Generation
on:
  push:
    branches:
      - main
      - feature/task_cwms_support
  pull_request:
    branches:
      - main
      - feature/task_cwms_support
permissions:
  contents: write
jobs:
  build-api-spec:
    name: Build OpenAPI Specification
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.2.2
      - name: Set up JDK 17
        uses: actions/setup-java@v5.0.0
        with:
          java-version: 17
          distribution: 'temurin'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.5.0
      - name: Generate OpenAPI
        run: ./gradlew generateOpenAPI
      - name: Upload OpenAPI Specification
        uses: actions/upload-artifact@v4.6.2
        with:
          name: openapi
          path: ./**/build/swagger/opendcs-openapi.json
          retention-days: 1
          if-no-files-found: error
